Project Name: "AI Research Agent"
Employee Name: "<I Vignesh Varma>"

models_used:
  - command-a-03-2025
  - llama-3.1-8b-instant
  - llama-3.3-70b-versatile
  - gemini-flash-latest
  - meta-llama/llama-3.1-70b-instruct
  - all-MiniLM-L6-v2
  - cross-encoder/ms-marco-MiniLM-L-6-v2

data:
  - synthetic
  - web_public_sources

tools:
  - fastapi
  - faiss
  - sentence-transformers
  - reportlab
  - tavily

evaluation:
  - automated

compute:
  platform: cloud
  gpu: none
